#!/bin/bash

while getopts ":m:n:" opt; do
  case $opt in
    m)

      echo "-m was triggered, Parameter: $OPTARG " >&2
      case $OPTARG in 
      	t)
			pt=threads
			echo $pt
			;;
		p)
			
			pt=processes
			echo $pt
			;;
		esac
      ;;
    n)
      echo "-n was triggered, Parameter: $OPTARG" >&2
      i=$OPTARG
      ;;
    \?)
      echo "Invalid option: -$OPTARG" >&2
      exit 1
      ;;
    :)
      echo "Option -$OPTARG requires an argument." >&2
      exit 1
      ;;
  esac
done


#Comentar la siguente linea para el proyecto

echo No thread/processes: $i P/T: $pt IF: $5  OF: $6

# ./main 