#!/bin/bash

while getopts ":m:n:::" opt; do
  case $opt in
    m)

      echo "-m was triggered, Parameter: $OPTARG " >&2
      case $OPTARG in 
      	t)
			echo threads
			r=threads
			;;
		p)
			echo processes
			pt=hola
			;;
		esac
      ;;
    n)
      echo "-n was triggered, Parameter: $OPTARG" >&2
      ;;
    \?)
      echo "Invalid option: -$OPTARG" >&2
      exit 1
      ;;
    :)
      echo "Option -$OPTARG requires an argument." >&2
      exit 1
      ;;
  esac
done

echo $pt
echo No thread/processes: $2 P/T: $4 IF: $5  OF: $6